### ISSUE TITLE
ArticleFeed implementation uses wrong logic

### ISSUE THREAD

**Issue by jldiaz** [yacoma/morepath-realworld-example-app#2]
According with RealWorld specs, [article feed](https://github.com/gothinkster/realworld/tree/master/api#feed-articles) should provide the list of articles published by followed users.

This means that if UserA "follows" UserB, the feed of UserA should show all posts created by UserB. This is not what happens.

Instead, UserA feed shows the articles created by all users which are following UserA. The problem is [this line](https://github.com/yacoma/morepath-realworld-example-app/blob/master/conduit/blog/collection.py#L59):

```python
        result = select(article for article in Article
                        for author in article.author
                        if self.user in author.follows)
```

which should be `author.followers` instead of `author.follows`.

Also, would be correct the following simplification?

```python
        result = select(article for article in Article
                        if self.user in article.author.followers)
```

**Comment by henri-hulski** [comment]
Great find! The simplification does also work. Thanks a bunch!

**Comment by henri-hulski** [comment]
After consulting the PonyORM author I found even a simpler way:
```python
    result = Article.select(lambda a: self.user in a.author.followers)
```
See b064caaa4b0042ffe76d0de3f2de1d6a59a7ce13.
